core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace="store"))
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views


app_name = 'store'


urlpatterns = [
	path("", views.store, name="store"),
	path("cart/", views.cart, name="cart"),
	path("checkout/", views.checkout, name="checkout"),

	path('update_item/', views.update_item, name="update_item"),
	path('process_order/', views.processOrder, name="process_order")
]

store/models.py
from django.db import models
from django.contrib.auth.models import User

from datetime import datetime


class Customer(models.Model):
	user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, blank=True)
	name = models.CharField(max_length=200, null=True)
	email = models.CharField(max_length=200, null=True)

	def __str__(self):
		return self.name


class Product(models.Model):

	name = models.CharField(max_length=200, null=True)
	price = models.DecimalField(max_digits=5,decimal_places=2)
	digital = models.BooleanField(default=False, null=True, blank=False)
	image = models.ImageField(null=True, blank=True)

	class Meta:
		verbose_name = "Product"
		verbose_name_plural = "Products"

	def __str__(self):
		return self.name

	@property
	def imageURL(self):
		try:
			url = self.image.url
		except Exception as e:
			url = ''
		return url
	


class Order(models.Model):

	customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
	date_ordered = models.DateTimeField(auto_now_add=True)
	complete = models.BooleanField(default=False, null=True, blank=False)
	transaction_id = models.CharField(max_length=200, null=True)

	class Meta:
		verbose_name = "Order"
		verbose_name_plural = "Orders"

	def __str__(self):
		return self.date_ordered.strftime('%Y-%m-%d')

	@property
	def get_cart_total(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.get_total for item in orderitems])
		return total

	@property
	def get_cart_items(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.quantity for item in orderitems])
		return total

	@property
	def shipping(self):
		shipping = False
		orderitems = self.orderitem_set.all()
		for i in orderitems:
			if i.product.digital == False:
				shipping = True
		return shipping																																															 
	


class OrderItem(models.Model):

	product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
	quantity = models.IntegerField(default=0, null=True, blank=True)
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name = "OrderItem"
		verbose_name_plural = "OrderItems"

	def __str__(self):
		return self.date_added.strftime('%Y-%m-%d')

	@property
	def get_total(self):
		return self.product.price * self.quantity
	
	

class ShippingAddress(models.Model):

	customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
	address = models.CharField(max_length=200, null=True)
	city = models.CharField(max_length=200, null=True)
	state = models.CharField(max_length=200, null=True)
	zipcode = models.CharField(max_length=200, null=True)
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name = "ShippingAddress"
		verbose_name_plural = "ShippingAddresss"

	def __str__(self):
		pass
	
	
	

store/views.py
from django.shortcuts import render
from django.http import JsonResponse

import json
from datetime import datetime
from decimal import Decimal

from .models import *
from .utils import cookieCart, cartData, guestOrder


def store(request):
	products = Product.objects.all()
	# if request.user.is_authenticated:
	# 	customer = request.user.customer
	# 	order, created = Order.objects.get_or_create(customer=customer, complete=False)
	# 	items = order.orderitem_set.all()
	# else:
	# 	items = []
	# 	order = {'get_cart_items': 0, 'get_cart_total': 0, 'shipping': False}
	context = {'products': products}
	return render(request, 'store/store.html', context)


def cart(request):

	data = cartData(request)

	items = data.get("items")
	order = data.get("order")

	context = {'items': items, 'order': order}
	return render(request, 'store/cart.html', context)


def checkout(request):
	data = cartData(request)

	items = data.get("items")
	order = data.get("order")
	context = {'items': items, 'order': order}
	return render(request, 'store/checkout.html', context)


def update_item(request):

	data = json.loads(request.body)
	productId = data.get('productId')
	action = data.get('action')

	print('Action:' ,action)
	print('productId', productId)

	customer = request.user.customer
	product = Product.objects.get(id=productId)

	order, created = Order.objects.get_or_create(customer=customer, complete=False)
	orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

	if action == "add":
		orderItem.quantity = orderItem.quantity + 1
	elif action == "remove":
		orderItem.quantity = orderItem.quantity - 1

	orderItem.save()

	if orderItem.quantity <= 0:
		orderItem.delete()

	return JsonResponse('Item was added', safe=False)


def processOrder(request):

	transaction_id = datetime.now().timestamp()
	data = json.loads(request.body)

	if request.user.is_authenticated:
		customer = request.user.customer
		order, created = Order.objects.get_or_create(customer=customer, complete=False)
		

	else:
		customer, order = guestOrder(request, data)

	total = Decimal(data['form']['total'])
	order.transaction_id = transaction_id

	if total == Decimal(order.get_cart_total):
		order.complete = True
	order.save()

	if order.shipping == True:
		ShippingAddress.objects.create(
			customer=customer,
			order=order,
			address=data['shipping']['address'],
			city=data['shipping']['city'],
			state=data['shipping']['state'],
			zipcode=data['shipping']['zipcode'],
			)

	return JsonResponse('Payment completed!', safe=False)

store/templates/store/cart.html
{% extends './main.html' %}
{% load static %}
{% block content %}
	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">
				<a href="{% url 'store:store' %}" class="btn btn-outline-dark">&#x2190; continue shopping</a>
				<br>

				<table class="table">
					<tr>
						<th>
							<h5>
								Items:
								<strong>{{order.get_cart_items}}</strong>
								
							</h5>
						</th>
						<th>
							<h5>
								Total:
								<strong>${{order.get_cart_total}}</strong>
								
							</h5>
						</th>
						<th>
							<a style="float: right;margin: 5px" class="btn btn-success" href="{% url 'store:checkout' %}">Checkout</a>
						</th>
					</tr>
				</table>
			</div>
			<br>
			<div class="box-element">
				<div class="cart-row">
					<div style="flex: 2"></div>
					<div style="flex: 2"><strong>Item</strong></div>
					<div style="flex: 1"><strong>Price</strong></div>
					<div style="flex: 1"><strong>Quantity</strong></div>
					<div style="flex: 1"><strong>Total</strong></div>
				</div>
				{% for item in items %}
				<div class="cart-row">
					<div style="flex: 2"><img class="row-image" src="{{item.product.imageURL}}" alt=""></div>
                    <div style="flex: 2">{{item.product.name}}</div>
                    <div style="flex: 1">${{item.product.price}}</div>
                    <div style="flex: 1">
                        <p class="quantity">{{item.quantity}}</p>
						<div class="quantity">
							<img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">
					
							<img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
						</div>
                    </div>
                    <div style="flex: 1">${{item.get_total}}</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

store/templates/store/checkout.html
{% extends './main.html' %}
{% load static %}
{% block content %}
	<div class="row">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">
				<form id="form">
					<div id="user-info">
						<div class="form-field">
							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>
						<div class="form-field">
							<input required class="form-control" type="email" name="email" placeholder="Email..">
						</div>
					</div>
					
					<div id="shipping-info">
						<hr>
						<p>Shipping Information:</p>
						<hr>
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="City..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="State..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="country" placeholder="Zip code..">
						</div>
					</div>

					<hr>
					<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
				</form>
			</div>

			<br>
			<div class="box-element hidden" id="payment-info">
				<small>Paypal Options</small>
				<button id="make-payment" class="btn btn-primary">Make payment</button>
				<div id="paypal-button-container"></div>
			</div>
			
		</div>

		<div class="col-lg-6">
			<div class="box-element">
				<a  class="btn btn-outline-dark" href="{% url 'store:cart' %}">&#x2190; Back to Cart</a>
				<hr>
				<h3>Order Summary</h3>
				<hr>
				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>${{item.product.price}}</p></div>
					<div style="flex:1"><p>x{{item.quantity}}</p></div>
				</div>
				{% endfor %}
				<h5>Items: {{order.get_cart_items}}</h5>
				<h5>Total:   ${{order.get_cart_total}}</h5>
			</div>
		</div>
	</div>

	<script type="text/javascript">
		var shipping = "{{order.shipping}}"
		var total = "{{order.get_cart_total}}"

		if (shipping === 'False') {
			document.getElementById('shipping-info').innerHTML = ""
		}

		if (user != "AnonymousUser") {
			document.getElementById('user-info').innerHTML = ""
		}

		if (shipping === 'False' & user != "AnonymousUser") {
			document.getElementById('form-wrapper').classList.add('hidden');
			document.getElementById('payment-info').classList.remove('hidden');
		}

		var form = document.getElementById('form')
		form.addEventListener('submit', function(e) {
			e.preventDefault();

			document.getElementById('form-button').classList.add('hidden');
			document.getElementById('payment-info').classList.remove('hidden');
		})

		document.getElementById('make-payment').addEventListener('click', function(e) {
			submitFormData()
		})

		function submitFormData() {
			console.log('Payment button clicked')

			var userFormData = {
				'name': null,
				'email': null,
				"total": total
			}

			var shippingInfo = {
				'address': null,
				'city': null,
				'state': null,
				'zipcode': null
			}

			if (shipping !== 'False') {
				shippingInfo.address = form.address.value;
				shippingInfo.city = form.city.value;
				shippingInfo.state = form.state.value;
				shippingInfo.zipcode = form.zipcode.value;
			}

			if (user === "AnonymousUser") {
				userFormData.name = form.name.value;
				userFormData.email = form.email.value;
			}

			var url = '/process_order/'

			fetch(url, {
				method: 'POST',
				headers: {
					'Content-Type': "application/json",
					'X-CSRFToken': csrftoken
				},
				body: JSON.stringify({
					'form': userFormData,
					'shipping': shippingInfo
				})

			}).then(response => {
					return response.json()
			}).then(data => {
				console.log('data', data);

				cart = {}
				document.cookie = `cart=${JSON.stringify(cart)};domain=;path=/`

				window.location.href = "{% url 'store:store' %}"
			})
		}


	</script>
{% endblock %}

store/templates/store/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>

	<!-- CSS only -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1">

	<script type="text/javascript">
		var user = '{{request.user}}';

		function getToken(name) {
		    let cookieValue = null;
		    if (document.cookie && document.cookie !== '') {
		        const cookies = document.cookie.split(';');
		        for (let i = 0; i < cookies.length; i++) {
		            const cookie = cookies[i].trim();
		            // Does this cookie string begin with the name we want?
		            if (cookie.substring(0, name.length + 1) === (name + '=')) {
		                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
		                break;
		            }
		        }
		    }
		    return cookieValue;
		}
		const csrftoken = getToken('csrftoken');

		function getCookie(name) {
			var cookieArr = document.cookie.split(';');

			for (var i =0 ; i< cookieArr.length; i++) {
				var cookiePair = cookieArr[i].split('=');

				if (name == cookiePair[0].trim()) {
					return decodeURIComponent(cookiePair[1])
				}
			}

			return null;
		}

		var cart = JSON.parse(getCookie('cart'))
		console.log("cart", cart)

		if (cart == undefined) {
			cart = {}
			console.log('Cart was created', cart)
			document.cookie = `cart=${JSON.stringify(cart)};domain=;path=/`
		}
	</script>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	  
	    <a class="navbar-brand" href="{% url 'store:store' %}">Ecom</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>

	    <div class="collapse navbar-collapse" id="navbarSupportedContent">
	      <ul class="navbar-nav me-auto">
	        <li class="nav-item">
	          <a class="nav-link active" aria-current="page" href="{% url 'store:store' %}">Store</a>
	        </li>
	        
	      </ul>

	      <div class="form-inline my-2 my-lg-0">
	      	<a href="#" class="btn btn-warning">Login</a>

	      	<a href="{% url 'store:cart' %}">
	      		<img id="cart-icon" src="{% static 'images/cart.png' %}" alt="">

	      	</a>
	      	<p id="cart-total">{{cart_items}}</p>
	      </div>
	    </div>
	  
	</nav>
	

	<div class="container">
		{% block content %}

		{% endblock %}
	</div>
	
	<!-- JavaScript Bundle with Popper -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

	<script text="text/javascript" src="{% static 'js/cart.js' %}"></script>
</body>
</html>

store/templates/store/store.html
{% extends './main.html' %}
{% load static %}
{% block content %}
	<div class="row">
		{% for product in products %}
		<div class="col-lg-4">
			<img class="thumbnail" src="{{product.imageURL}}">
			<div class="box-element product">
				<h6><strong>{{product.name}}</strong></h6>
				<hr>
				<button data-product="{{product.id}}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
				<a href="#" class="btn btn-outline-success">View</a>
				<h4 style="display: inline-block; float:right">${{product.price}}</h4>
			</div>
		</div>
		{% endfor %}
		
	</div>
	
{% endblock %}